language: python
python:
  - "3.7"
if: type = push
cache: pip

env:
  global:
    - NATHAN_PK: 5JkYKpRDWeY3DN4qjZRKpEfxCqmTX17fsBJhupE9DJVVmJoGh6C
    - INIT0_PK: 5J6azg8iUcQEbxEaLAFrJbcdBjgKqewLF81A63NE4T2aeHCsKiE
    - MIGRATION_RESULT: ""
  jobs:
    - PYTESTS_FILTERS: database_api
    - PYTESTS_FILTERS: ^database_api

install:  pip3 install -r requirements.txt
services:
  - docker
before_script:
  - docker-compose build
  - MIGRATION_RESULT=$(docker-compose run migrate)
  - export SIDECHAIN_ADDRESS=$(echo \"$MIGRATION_RESULT\" | perl -lne '/SideChain.*contract address:\s+(0x.{40})/ && print $1')
  - sed -i "s/0xc87395b45C1c199F25a6c2Be43515C41d53751Af/$SIDECHAIN_ADDRESS/g" ./genesis.json
  - docker-compose up -d ganache
  - docker-compose up -d echo
script:
  - python3 test_runner.py
